version: "3"
services:
    serverproxy:
        build: 
            context: ./serverProxy
        ports:
            - "80:443"
            - "443:443"
        volumes:
            - ./serverProxy/default.conf:/etc/nginx/conf.d/default.conf:ro
           # - ./serverProxy/certs:/etc/nginx/certs
    loginserver:
        container_name: nodeLogin
        build:
            context: ./loginDataServer
        environment:
            - NODE_ENV=development
    metadataserver:
        container_name: nodemeta
        build:
            context: ./metadataServer
        environment:
            - NODE_ENV=development
    streamingserver:
        container_name: nodestreaming
        build:
            context: ./streamingServer
        environment:
            - NODE_ENV=development
    imageserver:
        container_name: nodeimage
        build:
            context: ./imageServer
        environment:
            - NODE_ENV=development
    