version: "3"
services:
    react-app:
        container_name: react_container
        build:
            context: ./music-app
            dockerfile: react-app
        ports:
            - 3000:3000
        volumes:
            - ".:/app"
            - "/app/node_modules"
        environment:
             - NODE_ENV=production
        stdin_open: true
    serverproxy:
        build: 
            context: ./serverProxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./serverProxy/default.conf:/etc/nginx/conf.d/default.conf:ro
           # - ./serverProxy/certs:/etc/nginx/certs
    loginserver:
        container_name: nodeLogin
        build:
            image: unservice/login_service
        environment:
            - NODE_ENV=development
    metadataserver:
        container_name: nodemeta
        build:
            image: unservice/metadata_service
        environment:
            - NODE_ENV=development
    streamingserver:
        container_name: nodestreaming
        build:
            image: unservice/streaming_service_simple
        environment:
            - NODE_ENV=development
    imageserver:
        container_name: nodeimage
        build:
            image: unservice/image_service
        environment:
            - NODE_ENV=development
    