version: "3"
services:
    serverproxy:
        image: unservice/proxy:mono
        ports:
            - "80:443"
            - "443:443"
    loginserver:
        container_name: nodeLogin
        image: unservice/login_service:latest
    musicserver:
        container_name: nodemusic
        image: unservice/mono_music_server:latest