version: "3"
services:
    serverproxy:
        build: 
            context: ./serverProxy
        ports:
            - "80:443"
            - "443:443"
        volumes:
            - ./serverProxy/default.conf:/etc/nginx/conf.d/default.conf:ro
           # - ./serverProxy/certs:/etc/nginx/certs
    loginserver:
        container_name: nodeLogin
        image: unservice/login_service
        environment:
            - NODE_ENV=development
    metadataserver:
        container_name: nodemeta
        image: unservice/metadata_service
        environment:
            - NODE_ENV=development
    streamingserver:
        container_name: nodestreaming
        image: unservice/streaming_service_simple
        environment:
            - NODE_ENV=development
    imageserver:
        container_name: nodeimage
        image: unservice/image_service
        environment:
            - NODE_ENV=development
    