# BASE
FROM nginx:alpine

#copying certs into nginx
COPY /certs/ /etc/nginx/certs/
COPY /build/ /usr/share/nginx/html/


#copying configfile into nginx
COPY ./default.conf /etc/nginx/conf.d/default.conf

