FROM node:alpine

ENV NODE_ENV production

WORKDIR /app

COPY package.json ./package.json
COPY package-lock.json ./package-lock.json

RUN npm install

COPY ./streamingServer.js .
#COPY ./music ./music

EXPOSE 2040

CMD ["node", "streamingServer.js"]