FROM node:alpine

ENV NODE_ENV production

WORKDIR /app

COPY package.json ./package.json
COPY package-lock.json ./package-lock.json

RUN npm install

COPY ./metadataServer.js .

EXPOSE 2060

CMD ["node", "metadataServer.js"]