FROM node:alpine

ENV NODE_ENV production

WORKDIR /app

COPY package.json ./package.json
COPY package-lock.json ./package-lock.json

RUN npm install

COPY ./loginDataServer.js .
COPY ./User.js .

EXPOSE 8080

CMD ["node" ,"loginDataServer.js"]




