apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traffic-router
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: frontend-service
              servicePort: 100080
          - path: /image/*
            backend:
                serviceName: image-service
                servicePort: 102020
          - path: /login/*
            backend:
              serviceName: login-service
              servicePort: 108080
          - path: /metadata/*
            backend:
              serviceName: metadata-service
              servicePort: 102060
          - path: /streaming/*
            backend:
              serviceName: streaming-service
              servicePort: 102040
