FROM node:alpine


ENV NODE_ENV production

WORKDIR /app

COPY package.json ./package.json
COPY package-lock.json ./package-lock.json

RUN npm install

COPY ./images ./images

EXPOSE 2020

CMD ["node", "imageServer.js"]